test agistin

diff --git a/.github/workflows/selenium_testing.yml b/.github/workflows/selenium_testing.yml
--- a/.github/workflows/selenium_testing.yml
+++ b/.github/workflows/selenium_testing.yml
@@ -26,23 +26,13 @@ jobs:
       - name: Build React app
         run: npm run build --prefix ./frontend
 
-      - name: Prepare artifacts
-        run: |
-          tar -czvf frontend-build.tar.gz -C frontend/dist .
-          ls -l
-
-      - name: Upload artifacts
-        uses: actions/upload-artifact@v4
-        with:
-          name: frontend-build
-          path: frontend-build.tar.gz
-
   test:
     needs: build
     runs-on: ubuntu-latest
-
     container:
       image: node:20
+      ports:
+        - 5173:5173
       options: --network-alias=testserver
 
     env:
@@ -54,46 +44,38 @@ jobs:
         image: selenium/standalone-chrome
         ports:
           - 4444:4444
-        options: >-
-          --health-cmd="curl -f http://localhost:4444/wd/hub/status || exit 1"
-          --health-interval=10s
-          --health-timeout=5s
-          --health-retries=5
 
     steps:
-      - name: Download built frontend
-        uses: actions/download-artifact@v4
-        with:
-          name: frontend-build
+      - name: Checkout repository
+        uses: actions/checkout@v2
 
-      - name: Extract frontend build
+      - name: Install dependencies
+        run : npm install --prefix ./frontend
+
+      - name: List node_modules
+        run: ls -l node_modules
+
+      - name: List files for debugging
         run: |
-          mkdir -p frontend/dist
-          tar -xzvf frontend-build.tar.gz -C frontend/dist
-          ls -l frontend/dist
+          echo "Current directory:"
+          pwd
+
+      - name: Run unit tests
+        run: npm mocha ./frontend/selenium_testing/login_testing.js
 
       - name: Start Vite preview server
         run: |
-          npx vite preview --port 5173 --strictPort --host &
+          serve -s ./dist -l 5173 &
           sleep 5
 
-      - name: Wait for Vite server to start
+      - name: Verify server is running
         run: |
-          until curl -s $APP_URL > /dev/null; do
-            echo "Waiting for Vite server..."
-            sleep 2
-          done
+          curl -f http://localhost:3000 || { echo "Server failed to start"; exit 1; }
 
-      - name: Wait for Selenium server to be ready
+      - name: Wait for Selenium server to be up
         run: |
           for i in {1..10}; do
-            if curl -s $SELENIUM_REMOTE_URL/status | grep -q '"ready":true'; then
-              echo "Selenium is ready!"
-              break
-            else
-              echo "Waiting for Selenium..."
-              sleep 3
-            fi
+            curl -s $SELENIUM_HOST && break || sleep 3
           done
 
       - name: Run Selenium tests
