test agistin

diff --git a/.github/workflows/selenium_testing.yml b/.github/workflows/selenium_testing.yml
--- a/.github/workflows/selenium_testing.yml
+++ b/.github/workflows/selenium_testing.yml
@@ -36,7 +36,7 @@ jobs:
       options: --network-alias=testserver
 
     env:
-      APP_URL: http://host.docker.internal:5173
+      APP_URL: http://testserver:5173
       SELENIUM_HOST: http://selenium:4444/wd/hub
 
     services:
@@ -70,7 +70,7 @@ jobs:
 
       - name: Verify server is running
         run: |
-          curl -f $APP_URL || { echo "Server failed to start"; exit 1; }
+          curl -f http://localhost:5173 || { echo "Server failed to start"; exit 1; }
 
       - name: Wait for Selenium server to be up
         run: |
